# DataSource Config
server:
  port: 8083
  ssl:
    key-store: classpath:ichuang.xyz.jks
    key-store-type: JKS
    key-store-password: 963592390li
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vueblog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root
  redis:
      host: localhost
      timeout: 5000
  mail:
      host:  smtp.163.com
      username: 15054656072@163.com
      password: 1230ASD
      default-encoding: UTF-8
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
fanli:
  jwt:
    # 部署上线务必修改此配置，以保证token的安全性
    secret: f4e2e52034348f86b67cde581c0f9eb5
    expire: 172800
    header: token


admin:
  qiniu:
    access-key: _Z9-phMig4Rs6tKEX-B3Y3LtB6PNLcwKqNkwKgHD
    secretKey: MpA7EOjKPTeZQ6-xkAlcXbKC6uhS2LmMt1NpG8aw
    bucket: ichuang-xyz-imags
logging:
  file:
    name: logs/lab.log